### ISSUE TITLE
Link unproceedings to previous meetings

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/pyastro#29]
E.g. http://python-in-astronomy.github.io/2016/ should have a link to the unproceedings somewhere

**Comment by bsipocz** [comment]
Never mind, now I see that's an outdated page. In that case, it would be nice to fully get rid of it...

**Comment by wtbarnes** [comment]
This issue should be moved to [this repo](https://github.com/python-in-astronomy/python-in-astronomy.github.io)
