### ISSUE TITLE
Multiple logos

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/pyastro#53]
There are two logos on the main page: the usual openastronomy one and a derived version of the Python language logo. I think it would be better to settle on one or the other and use it consistently. I'm in favor of the former as it is already used throughout the openastronomy webpage. Additionally, there can be complications with [derived versions of the Python logo](https://www.python.org/psf/trademarks/).

**Comment by Cadair** [comment]
The first is the openastro logo and the other is the pyastro logo :man_shrugging:

**Comment by wtbarnes** [comment]
Could we just use the pyastro logo?

**Comment by bsipocz** [comment]
Sorry, but no. The openastronomy is not only for python, thus the pyastro logo is not appropriate. 

But why is it an issue to have two logos?

**Comment by wtbarnes** [comment]
No issue. I just wasn't initially sure why there were two, but seems pretty clear now.
