### ISSUE TITLE
pyastro 2020 LOC

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/pyastro#56]
The 2020 meeting webpage needs a list of the members on the local organizing committee (LOC)

**Comment by drsophiemurray** [comment]
List of LOC members:
- Dúalta Ó Fionnagáin (TCD)
- Simon Purser (DIAS)
- Ciara Maguire (TCD/DIAS)
- Shane Maloney (TCD/DIAS)
- David McKenna (DIAS/TCD)
- Pearse Murphy (TCD/DIAS)
- Sophie Murray (TCD/DIAS; Chair)

**Comment by wtbarnes** [comment]
Thanks @drsophiemurray!
