### ISSUE TITLE
pyastro 2020 lodging info

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/pyastro#57]
Need to add info on lodging for the 2020 meeting page

**Comment by drsophiemurray** [comment]
@wtbarnes some text for the webpage below :)

A limited number of rooms have been reserved at the [Ballsbridge Hotel, Pembroke Road Ballsbridge, Dublin, D04 D687.](https://www.ballsbridgehotel.com) To avail of the conference bed and breakfast rate, please book via this weblink before 9 March 2020: [https://bookings.ballsbridgehotel.com/offer/python-in-astronomyc](https://bookings.ballsbridgehotel.com/offer/python-in-astronomyc)

This hotel is approximately 25 minutes walk from the conference venue in Trinity College (use the Lincoln Place entrance), or a short journey on public transport (nearest DART station is at Lansdowne Road and nearest bus stop is at the American Embassy). We recommend attendees get a [Leap Card](https://about.leapcard.ie/leap-visitor-card) for the duration of their stay if they plan to use public transport.

Some other hotels closer to the venue include:
- [Trinity City Hotel](https://www.trinitycityhotel.com/) on Pearse Street
- [The Davenport Hotel](https://www.davenporthotel.ie), [The Alex Hotel](https://www.thealexhotel.ie) and [The Mont Hotel](https://www.themonthotel.ie) all around Merrion Square.
- [Buswells Hotel](https://www.buswells.ie) on Molesworth Street.

There are also a variety of Airbnb options across the city. Feel free to ask the LOC about areas in Dublin on the PyAstro Slack logistics channel!

**Comment by SolarDrew** [comment]
One comment: please can we refer to the chat room, rather than to slack channels? I'm clearly not winning the debate on dropping slack and that's fine, but since we are using both slack and matrix I'd like for them to be treated equally rather than promoting one as the 'proper' chat room and the other as a lesser-known alternative.

That aside, thanks for this @drsophiemurray :+1:

**Comment by drsophiemurray** [comment]
Oops sorry @SolarDrew and thanks for spotting 😅 I forgot about Riot yet again, definitely just call it chat room!
