### ISSUE TITLE
Advertise PyAstro 2020 application

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/pyastro#60]
We should advertise that the PyAstro 2020 application is now open through the following channels:

- Twitter: 
   - [x] PyAstro
   - [x] Astropy
   - [x] SunPy
   - [x] OpenAstronomy
- Facebook
  - [x] Python in Astronomy
- Collaborations
  - [x] LIGO
  - [ ] EHT
  - [x] XENON1T
- Mailing Lists:
  - [x] UK Solar Physics News
  - [x] SPD AAS SolarNews
  - [x] SunPy (user and dev)
  - [x] Astropy (dev)
  - [x] OpenAstronomy
  - [x] yt (user and dev)
  - [x] PlasmaPy
  - [x] PyHC
  - [x] Chianti
- Slack/Riot Chats
  - [x] SunPy
  - [x] Astropy
  - [x] PyHC
  - [ ] LSST
  - [x] PlasmaPy
  - [x] PyAstro
- Flier to university departments / observatories / labs (?)

**Comment by bsipocz** [comment]
Please do try to advertise beyond the solar community, too, e.g many astronomers are not on any of these lists. Some examples:

- python in astronomy facebook group
- lsst slack
- reach out to ligo and eht folks to forward the ad to their forums
- digital fliers to the observatories rather than university departments (most software groups are in fact in labs/observatories)

**Comment by wtbarnes** [comment]
@bsipocz Thanks for the feedback! I've updated the list above as well.

**Comment by wtbarnes** [comment]
Form letter to use for all mailing lists:

> Dear colleagues,
>
>It is my pleasure to announce that applications are now open for Python in Astronomy 2020, to be held 20 - 24 April 2020 at Trinity College, Dublin in Dublin, Ireland.
>
> Though the application form will be open until 23:59 UTC on 6 January 2019, I encourage you to complete the form soon to make sure you don’t miss the deadline.
>
> The application form is at: https://forms.gle/mtdm6QKENdY8Y1Ph9
>
> More information about the conference, including links to past years, is available at: http://openastronomy.org/pyastro/2020/ 
>
> Finally, a brief excerpt from the description of the conference:
>
> In addition to sharing information about state-of-the art Python Astronomy packages, the workshop will focus on improving interoperability between astronomical Python packages, mentoring current open-source contributors, and developing educational materials for Python in Astronomy. The meeting is therefore not only aimed at current developers, but also educators and research group leaders who are interested in being involved in these efforts.
>
> Participant selection will be made with the goal of enhancing the Python in Astronomy community and we encourage requests to attend from all career levels. Effort will also be made to select participants who have contributed meaningfully to the Python in Astronomy ecosystem via providing educational materials, documentation, and/or code contributions. This conference is neither intended to be an introduction to Python nor only for expert-level Python developers.
>
> Thanks,
>
>  (name of poster)
>
> On behalf of the SOC: Monica Bobra (co-chair), Andrew Leonard (co-chair), Will Barnes, Clara Brasseur, Juan Luis Cano, Rebecca Lange, Sophie Murray

Announcements in Twitter/Slack/Riot could be:

> Applications for Python in Astronomy 2020 are now open! The conference will be held from 20 - 24 April 2020 at Trinity College, Dublin. You can apply here: https://forms.gle/mtdm6QKENdY8Y1Ph9. More information about the conference is available here: http://openastronomy.org/pyastro/2020/

**Comment by wtbarnes** [comment]
As the due date for applications nears, we should also try to remember to post notifications on chats, mailing lists, etc. to remind people to submit before the deadline.

**Comment by ceb8** [comment]
@wtbarnes I posted to the Python in Astronomy FB group (can't update the checklist).

**Comment by wtbarnes** [comment]
Thanks @ceb8! I updated the checklist

**Comment by wtbarnes** [comment]
Does anyone know the best points of contact for LSST, EHT, and LIGO (i.e. mailing lists, Slack, etc.)? A bit of googling has not turned up anything useful.
