### ISSUE TITLE
Twitter handle name for 2020 meeting

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/pyastro#62]
In past years, a new Twitter account has been created for each meeting (pyastro18, pyastro19, etc.)

Currently, the link on the page is to pyastro20 which is a nonexistent account. We need to decide whether we want to make a new account with this name or make a more general Python in Astronomy twitter handle and use that for all future meetings.

**Comment by astrojuanlu** [comment]
+1 for a handle we can reuse every year (and changing hashtags)

**Comment by drsophiemurray** [comment]
New account [@pythoninastro](https://twitter.com/pythoninastro) is live! We should add a link to it on the website.

**Comment by wtbarnes** [comment]
Closed by #64
