### ISSUE TITLE
Add sponsor logos for 2020 meeting

### ISSUE THREAD

**Issue by wtbarnes** [OpenAstronomy/pyastro#70]
Once we finalize our sponsors, the appropriate logos need to be added to the bottom of the page.

**Comment by Tanish2000** [comment]
Have you finalized your sponsers

**Comment by ywalia01** [comment]
Hello @wtbarnes I'd like to work on this provided the sponsors have been finalized

**Comment by wtbarnes** [comment]
Sorry for the lack of response. This meeting is long past.
